import{access,readFile,readdir,stat}from'node:fs/promises';import{join}from'node:path';
const required=['index.html','privacy/index.html','404.html','robots.txt','sitemap.xml','styles.css','runtime-config.js','js/app.js','js/game.js','js/puzzles.js','assets/icon.svg','assets/social-card.svg','site.webmanifest'];await Promise.all(required.map(file=>access(join('dist',file))));
async function filesIn(directory){const files=[];for(const entry of await readdir(directory,{withFileTypes:true})){const path=join(directory,entry.name);entry.isDirectory()?files.push(...await filesIn(path)):files.push(path)}return files}
for(const path of await filesIn('src')){const content=await readFile(path,'utf8');if(/{{(?!SITE_URL}})[^{}]+}}/.test(content))throw new Error(`Unresolved source token in ${path}`);if(/(?:TODO|TBD|lorem ipsum|example\.com|\.invalid|YOUR[_-](?:ID|KEY))/i.test(content))throw new Error(`Placeholder in ${path}`)}
for(const file of required.filter(file=>/\.(html|txt|xml|js)$/.test(file))){const content=await readFile(join('dist',file),'utf8');if(/{{[^{}]+}}/.test(content))throw new Error(`Unresolved token in ${file}`)}
const html=await readFile('dist/index.html','utf8');for(const[name,re]of[['title',/<title>/],['description',/meta name="description"/],['canonical',/rel="canonical"/],['Open Graph',/property="og:title"/],['Twitter',/name="twitter:card"/],['structured data',/application\/ld\+json/],['main heading',/<h1/],['privacy',/href="\/privacy\/"/]])if(!re.test(html))throw new Error(`Missing ${name}`);
const app=await readFile('dist/js/app.js','utf8');if(/\.innerHTML\s*=|insertAdjacentHTML|localStorage|sessionStorage|document\.cookie/.test(app))throw new Error('Unsafe rendering or persistence found');
const runtimeFiles=(await filesIn('dist')).filter(path=>/\.(html|js|css)$/.test(path));const joined=(await Promise.all(runtimeFiles.map(path=>readFile(path,'utf8')))).join('\n');const siteOrigin=new URL(JSON.parse(await readFile('site.config.json','utf8')).siteUrl).origin;for(const match of joined.matchAll(/https?:\/\/[^\s"'<>`]+/g)){const url=new URL(match[0]);if(url.origin!==siteOrigin&&url.origin!=='http://www.w3.org'&&url.origin!=='https://schema.org'&&url.hostname!=='localhost'&&url.hostname!=='127.0.0.1')throw new Error('Unexpected external runtime URL')}
const css=await readFile('dist/styles.css','utf8');for(const token of['@media(max-width:340px)','prefers-reduced-motion','focus-visible'])if(!css.includes(token))throw new Error(`Missing CSS requirement: ${token}`);const social=await readFile('dist/assets/social-card.svg','utf8');if(!/width="1200" height="630"/.test(social))throw new Error('Bad social image size');let size=0;for(const path of await filesIn('dist'))size+=(await stat(path)).size;console.log(`Build checks passed. Dist size: ${(size/1024).toFixed(1)} KiB.`);
